Pad buttons
artrmz/flutter_control_pad pull request #10
Opened 2019-06-25 14:05 UTC by dudeck

2019-06-25 14:19 UTC, PabloPL requested changes

2019-06-25 14:19 UTC, PabloPL commented on lib/models/pad_button_item.dart
> +      {this.index,
Maybe we could use @required + assert to indicate what parameters are required to work?

2019-06-25 14:19 UTC, PabloPL commented on lib/views/circle_view.dart
> +      Center(child: (buttonImage != null) ? buttonImage : Text(buttonText)),
Maybe we could set that Text(buttonText) "default value" for buttonImage.
This way here we would have just
> child: Center(child: buttonImage),

2019-06-25 14:19 UTC, PabloPL commented on lib/views/circle_view.dart
> +        this.buttonText = ""});
Add comma here after "}" + reformat

2019-06-25 14:19 UTC, PabloPL commented on lib/models/pad_button_item.dart
> +      this.supportedGestures = const [Gestures.TAP]});
Add comma here after "}" + reformat

2019-06-25 14:19 UTC, PabloPL commented on lib/views/pad_button_view.dart
> +    this.size,
@required + assert

2019-06-25 14:19 UTC, PabloPL commented on lib/views/pad_button_view.dart
> +    double degrees = 360 / buttons.length * index;
What if we pass buttons as zero-length array? Maybe we could add some assert (for example in constructor)

2019-06-25 14:48 UTC, dudeck reviewed
@PabloPL updated PR after your comments. Please rereview ;)

2019-06-25 14:56 UTC, PabloPL approved these changes

2019-06-26 05:45 UTC, artur-ios-dev approved these changes

2019-06-26 05:49 UTC, merged